### ISSUE TITLE
[NEW SECTION] ✨ Documentation and data management

### ISSUE THREAD

**Issue by lauren-cadwallader** [very-good-science/our-handbook#33]
Please fill in the following:

**Summary of your suggestion**
A resource outlining how best to manage documentation.

**Is this an idea for a new resource, or an improvement to one?**
new

**Why would this resource be useful?**
1-2 sentences

**Content**
- Data documentation
- File naming
- Where to store data
- Backing up data

---

Please answer the following if it's a suggestion for a NEW resource:

**Where should it go in the book?**
Should be linked to tools #5 

**Is there an existing resource that we could link to instead?**
https://the-turing-way.netlify.app/project-design/filenaming.html is a good start. I think there are also Jisc guides about this kind of thing.

**Comment by NatalieThurlby** [comment]
Closed by #35
