### ISSUE TITLE
[NEW SECTION] ✨ One-to-Ones

### ISSUE THREAD

**Issue by lauren-cadwallader** [very-good-science/our-handbook#36]
**What's your idea for the new book section?**
Rules/guidance about how 1-1s should be conducted.

**Where should it go in the book?**
In the 'how we work' section

**Is this information available anywhere else?**
Not sure

**Why would this section be useful?**
Helps everyone get the most out of meetings. Shapes expectations.

**What will be in this section**
- General guidance for 1-1s
- Responsibilities of the supervisor
- Responsibilities of the researcher/student

**Additional context**
Should compliment the page of group meetings

**Comment by lauren-cadwallader** [comment]
I'll tackle this now

**Comment by jatonline** [comment]
I'll link to this in group-meetings.md when I make it :)

**Comment by NatalieThurlby** [comment]
Closed by #38
