### ISSUE TITLE
[NEW SECTION] ✨ Journal club

### ISSUE THREAD

**Issue by lauren-cadwallader** [very-good-science/our-handbook#55]
**What's your idea for the new book section?**
Information about the Group's journal club or how to find a journal club

**Where should it go in the book?**
How we work section

**Is this information available anywhere else?**
There are loads of resources online about journal clubs

**Why would this section be useful?**
Sets expectations if a club is already running or offers group members advice if they wish to join/start one.

**What will be in this section**
Groups with a journal club:
- When and where they are
- Expectations
- Reading for the next club
- Past papers discussed

Groups without a club:
- clubs they could join

**Comment by lauren-cadwallader** [comment]
I'll see if I can get this done in the next 6 minutes!!

**Comment by jatonline** [comment]
Thanks @lauren-cadwallader this is great content and supplementary links. Thanks for helping us during the sprint!! :)

**Comment by jatonline** [comment]
Thanks @lauren-cadwallader this is great content and supplementary links. Thanks for helping us during the sprint!! :)
